#ifeq ($(findstring 86, $(ProgramFiles)), )
#	PROGFILES := C:/Program Files
#else
	PROGFILES := C:/Program Files (x86)
#endif

GNU_INSTALL_ROOT := $(PROGFILES)/GNU Tools ARM Embedded/6 2017-q2-update
GNU_VERSION := 6.3.1
GNU_PREFIX := arm-none-eabi

